# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Applied Quantitative Methods
tagline:          'An open course'
description:      'Teaching students how to build and interpret models in R'
url:              dmcglinn.github.io/quant_methods
baseurl:          /quant_methods/

author:
  name:           'Dan McGlinn'
  url:            https://twitter.com/danmcglinn

github:
  repo:           https://github.com/dmcglinn/quant_methods
